### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'producer')

### ISSUE THREAD

**Issue by ari-party** [d00ML0rDz/NsfwSpy.js#3]
```
$ node .
2023-07-09 16:20:01.450460: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
\node_modules\@tensorflow\tfjs-converter\dist\tf-converter.node.js:30397
        this.version = graph.versions.producer + "." + graph.versions.minConsumer;
                                      ^

TypeError: Cannot read properties of undefined (reading 'producer')
    at GraphModel.loadSync (\node_modules\@tensorflow\tfjs-converter\dist\tf-converter.node.js:30397:39)
    at \node_modules\@tensorflow\tfjs-converter\dist\tf-converter.node.js:30373:72

Node.js v18.14.2
```
![image](https://github.com/NsfwSpy/NsfwSpy.js/assets/49074962/1e0074ad-8de5-404f-98d1-397a0edaf5fb)
![image](https://github.com/NsfwSpy/NsfwSpy.js/assets/49074962/1b8968b8-f2a7-4f4c-9f69-990d00c88e1e)
![image](https://github.com/NsfwSpy/NsfwSpy.js/assets/49074962/bec4629f-3dac-49a9-9aa2-21af3bb949d1)

**Comment by d00ML0rDz** [comment]
Hey, thanks for the issue.

It looks like your model path may be incorrect as it will be relative from the file you're running NsfwSpy from. Can you try using the following path and see if that fixes it?

```javascript
const nsfwSpy = new NsfwSpy("file://./models/model.json");
```

**Comment by ari-party** [comment]
Hi yeah, that seemed to resolve the issue.
